checks:
    javascript: true

#build:
    #dependencies:
        #before:
            #- npm install istanbul   # or add it as part of your package.json

build:
    nodes:
        analysis:
            tests:
                before:
                    environment: {JWT_SECRET: "hemlighet"}
                override:
                    -   command: 'npm run test-scrutinizer'
                        coverage:
                            file: 'coverage/clover.xml'
                            format: 'clover'
