checks:
    javascript: true

#build:
    #dependencies:
        #before:
            #- npm install istanbul   # or add it as part of your package.json

build:
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run

    tests:
        override:
            -
                #command: 'istanbul cover --report clover test.js'
                command: 'npm run test-scrutinizer'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
