checks:
    javascript: true

#build:
    #dependencies:
        #before:
            #- npm install istanbul   # or add it as part of your package.json

build:
    environment:
        variables:
            JWT_SECRET: "hemlighet"
            NODE_ENV: "test"
        node: "v10.14.2"
    nodes:
        analysis:
            tests:
                override:
                    -   command: 'npm run test-scrutinizer'
                        coverage:
                            file: 'coverage/clover.xml'
                            format: 'clover'
        analysis2:
            tests:
                override:
                    -   js-scrutinizer-run
